[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.78.2"
HUGO_THEME = "uBlogger"
HUGO_BASEURL = "https://datola.netlify.app"

[build.environment]
HUGO_VERSION = "0.78.2"
HUGO_THEME = "uBlogger"
HUGO_BASEURL = "https://datola.netlify.app"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
